draft

diff --git a/_drafts/pub b/_drafts/pub
--- a/_drafts/pub
+++ b/_drafts/pub
@@ -45,15 +45,15 @@ if [ `diff $Filename ../_posts/$DestFile | wc -l` -ne 2 ]; then
   echo "Something wrong. Stop. Check ../_posts/$DestFile"; exit
 fi
 echo "Committing to repository."
-cd ../_posts
-git add $DestFile || { echo "git add failed. Stop."; exit; }
-git commit -m "Published on "$Site_URL || { echo "Commit failed. Stop."; exit; }
+cd ../_posts || { echo "cd ../_posts failed. Stop."; exit; }
+git add $DestFile || { echo "git add $DestFile at ../_posts failed. Stop."; exit; }
+git commit -m "Published on "$Site_URL || { echo "Commit at ../_posts failed. Stop."; exit; }
 echo "Pushing to master repository."
-git push origin master || { echo "Push failed. Stop."; exit; }
+git push origin master || { echo "Push ../_posts failed. Stop."; exit; }
 echo "Published successfully."
 echo "Removing draft."
-cd ../_drafts
-git rm $Filename || { echo "git rm failed. Stop."; exit; }
+cd ../_drafts  || { echo "cd ../_drafts failed. Stop."; exit; }
+git rm $Filename || { echo "git rm $Filename failed. Stop."; exit; }
 git commit -m "Remove draft because it was published" || { echo "Commit failed. Stop."; exit; }
 git push origin master || { echo "Push failed. Stop."; exit; }
 echo "Draft removed successfully."
