-f option for git rm

diff --git a/_drafts/pub b/_drafts/pub
--- a/_drafts/pub
+++ b/_drafts/pub
@@ -63,7 +63,7 @@ git commit -m "Published on "$Permalink || \
    { echo "Commit at ../_posts failed. Stop."; exit; }
 echo "Removing draft."
 cd ../_drafts  || { echo "cd ../_drafts failed. Stop."; exit; }
-git rm $Filename || { echo "git rm $Filename failed. Stop."; exit; }
+git rm -f $Filename || { echo "git rm $Filename failed. Stop."; exit; }
 git commit -m "Remove draft because it was published" || \
    { echo "Commit failed. Stop."; exit; }
 echo "Pushing to master repository."
